### PR TITLE
Added support for importing a coreference table from a TSV. Closes #1401

### LINKED ISSUE #1401: Automatic construction of the coreference table based on the Levenshtein distance
Based on https://github.com/EHRI/ehri-entity-matcher which gives the user the possibility to match some names to vocabulary terms. I was wondering if something similar could be integrated in the portal in order to build the coreference table. An idea to improve it would be to use the Levenshtein distance in order to give the user a metric on how near is this vocabulary term (using multilingual labels) to those in the collections' access points Then, s/he can supervise the results and select the correct ones or just accept the ones whose distance is below a given threshold.

### PR DESCRIPTION
**Pull request by herminiogg**
Hi,

I've added support for importing a coreference table from a TSV file. As you can see in the image below, a textarea is provided to paste the TSV. After clicking the "Copy from TSV" the TSV is copied to the coreference table in the bottom of the page. The button "Save Coreference Table" was modified to accept both mechanisms of working. If some content was copied from a TSV it will save the contents of the TSV to the database, otherwise it will work as it used to do.

coreferenceFromTSV

### CODE REVIEW

**Comment by mikesname** [comment]
Awesome! Is this super urgent to get deployed? If not I'd like to suggest some changes to improve this area as a whole, since you're already working on it. But that could wait for later if you're keen to use it now. Anyway, I'll add a few review comments for minor things...

**Comment by mikesname** [comment]
As I said, this could wait for later but from the UI standpoint I would prefer it if there was an "import CSV" button which opened a modal with the textarea for you to paste into and then another button to run the import (much like the Create Snapshot UI works)

**Comment by herminiogg** [comment]
OK, thanks!

I will do more tests and give it some thought!

**Comment by herminiogg** [comment]
I have changed a bit the behavior of this screen. The textarea is only showed when we click the Copy from TSV (see the two attached screenshots) button and it disappears again when the coreference table form the TSV is finally saved. I think that this workflow makes things a bit clearer.
coreferenceFromTSVNew1
coreferenceFromTSVNew2

**Comment by mikesname** [comment]
@herminiogg yes I think that works better! A few changes I think would improve the patch:

 - change `importFromTSVHidden` to `importFromTsv` (and flip the polarity, so false to true)
 - change the "Copy from TSV" button to read "Import from TSV" and give it style `btn-default` instead of `btn-success`
 - instead of making the button disappear when the paste box is open, just disable it (with `v-bind:disabled="importFromTsv"`)
 - instead of having two buttons ("Copy from TSV" and "Save copied references") just have one button to save them if the user has pasted in valid data (I think having two buttons with one just setting the `this.references` variable is confusing)
 - add a "Cancel" button (with style `btn-default`) alongside the "Save copied references" buttons to close the panel if the user wants to abort the operation

I hope that makes sense and you don't find these comments too pedantic.

**Comment by herminiogg** [comment]
@mikesname I have followed your suggestions and the changes are implemented. Only two remarks on things that I have done differently:
- `v-bind:disabled` is not working for me. I don't know why but it didn't work either in my previous iteration where I tried to make something similar to what you suggested. I think that making it disappear is not too dramatic and the best option will be to have a toggle button, but having the cancel button seems good enough.
- Every time that something is pasted in the textarea the coreferences table on screen is updated on the fly. I think this is better than doing all in one go as at least you have time to review the result.

Don't worry about the comments, I feel is looking great thanks to them but at the same time maybe we are polishing too much something that is only going to be used by very few users (mainly you and me) 😅

**Comment by mikesname** [comment]
@herminiogg Great, looks good!

> v-bind:disabled is not working for me. I don't know why but it didn't work either in my previous iteration where I tried to make something similar to what you suggested. I think that making it disappear is not too dramatic and the best option will be to have a toggle button, but having the cancel button seems good enough.

Weird, works for me... anyway, I'll merge this.

> at the same time maybe we are polishing too much something that is only going to be used by very few users (mainly you and me) 

Probably true. Still I think I might revisit this area since I was quite confused about code I myself wrote and what it was supposed to do... :shrug:

**Pull request merged**
